# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
variables:
  GIT_STRATEGY: clone
stages:
- test
- build
- docker
- deploy
maven-test:
  image: maven:3.8.3-openjdk-17
  stage: test
  script:
  - ./mvnw clean
  - ./mvnw test
  - cat target/site/jacoco/index.html
maven-package:
  image: maven:3-jdk-8
  stage: build
  script:
  - ./mvnw clean
  - ./mvnw package -DskipTests
  artifacts:
    paths:
    - target/*.jar

docker-image:
  tags:
    - shell
  stage: docker
  script:
    - ./mvnw clean
    - ./mvnw package -DskipTests
    - docker build -t myapp:v1 .

maven-deploy:
  image: maven:3-jdk-8
  stage: deploy
  script:
  - echo ok.

include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
