version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.20.2
    container_name: fyp_offer_master_reverse_proxy
    depends_on:
      - fyp_offer_master_springboot_admin
      - fyp_offer_master_springboot
      - fyp_offer_master_vue_user
      - fyp_offer_master_vue_admin
    volumes:
      - ./nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - offer_master_network

  fyp_offer_master_springboot_admin:
    image: echocool/fyp_offer_master_springboot_admin:${VERSION:-latest}
    container_name: fyp_offer_master_springboot_admin
    expose:
      - "8081"
    networks:
      - offer_master_network
    restart: on-failure

  # springboot backend
  fyp_offer_master_springboot:
    image: echocool/fyp_offer_master_springboot:${VERSION:-latest}
    container_name: fyp_offer_master_springboot
    build:
      context: ./springboot-offer-master
    depends_on:
      - fyp_offer_master_springboot_admin
      - fyp_offer_master_db
    environment:
      - SERVER_ADDRESS=fyp_offer_master_springboot
      - DB_URL=jdbc:mysql://fyp_offer_master_db:3306/offermaster
      - DB_USERNAME=root
      - DB_PASSWORD=offermaster
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure


  # user portal
  fyp_offer_master_vue_user:
    image: echocool/fyp_offer_master_vue_user:${VERSION:-latest}
    container_name: fyp_offer_master_vue_user
    build:
      context: ./vue-user
    depends_on:
      - fyp_offer_master_springboot
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure


  # admin portal
  fyp_offer_master_vue_admin:
    image: echocool/fyp_offer_master_vue_admin:${VERSION:-latest}
    container_name: fyp_offer_master_vue_admin
    build:
      context: ./vue-admin
    depends_on:
      - fyp_offer_master_springboot
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure

  fyp_offer_master_django_ml:
    image: echocool/fyp_offer_master_django_ml:${VERSION:-latest}
    container_name: fyp_offer_master_django_ml
    build:
      context: ./django_ml
    depends_on:
      - fyp_offer_master_springboot
    expose:
      - "8080"
    networks:
      - offer_master_network
    restart: on-failure

  fyp_offer_master_minio:
    image: echocool/fyp_offer_master_minio
    ports:
      - "9000:9000"
      - "9090:9090"
    networks:
      - offer_master_network
    volumes:
      - ~/.fyp_offer_master/minio/data:/data
    environment:
      MINIO_ROOT_USER: group7
      MINIO_ROOT_PASSWORD: group7group7
    command: server /data --console-address ":9090"

  fyp_offer_master_portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8800:8000"
      - "9900:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.fyp_offer_master/portainer/data:/data
  fyp_offer_master_db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=offermaster
      - MYSQL_ROOT_PASSWORD=offermaster
    expose:
      - "3306"
    networks:
      - offer_master_network
    volumes:
      - ~/.fyp_offer_master/db:/var/lib/mysql

  fyp_offer_master_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fyp_offer_master_phpmyadmin
    environment:
      PMA_HOST: fyp_offer_master_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      - offer_master_network
    ports:
      - "8088:80"

networks:
  offer_master_network:
