name: Docker-compose build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build with Maven
#        run: mvn package -DskipTests --file pom.xml
#      - run: docker-compose --version
#      - name: Build with docker-compose
#        run: docker-compose build --parallel
#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: echo-cool
#          password: ${{ secrets.PACKAGE_TOKEN }}
#      - run: docker-compose push
      - run: mkdir -p ~/.ssh && echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan "${{ secrets.HOST }}" >> ~/.ssh/known_hosts
      - run: ssh -C ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
                          cd /root/COMP3032J-Degree-Project-Offer-Master-Group-7/;
                          pwd;
                          ls;
                          bash update_and_deploy.sh;"



