name: Docker-compose build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -DskipTests --file pom.xml
      - run: docker-compose --version
      - name: Build with docker-compose
        run: docker-compose build --parallel
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: echo-cool
          password: ${{ secrets.PACKAGE_TOKEN }}
      - run: docker-compose push
#      - run: docker image push ${{ env.REGISTRY }}/echo-cool/fyp/fyp_offer_master_springboot:latest
#      - run: docker image push ${{ env.REGISTRY }}/echo-cool/fyp/fyp_offer_master_vue_user:latest
#      - run: docker image push ${{ env.REGISTRY }}/echo-cool/fyp/fyp_offer_master_vue_admin:latest
