name: Docker-compose build

on:
  push:
    tags:
      - 'v*.*.*'


env:
  REGISTRY: ghcr.io

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#      - name: Build with Maven
#        run: mvn package -DskipTests --file pom.xml
#      - run: cd  springboot-admin
#      - run: mvn package -DskipTests --file pom.xml
#      - run: cd ..
      - run: docker-compose --version
      - name: Build with docker-compose
        run: docker-compose build --parallel
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: echo-cool
          password: ${{ secrets.PACKAGE_TOKEN }}
      - run: docker-compose push



